In [3]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.initializers import RandomNormal
import numpy

import pandas as pd
import matplotlib.pyplot as plt


In [6]:
facialVectors = pd.read_csv("X.csv")
indicatorEmotion = pd.read_csv("Y.csv")

In [5]:
facialVectors

-0.94  -1.03  -1.14  -2.50  -2.72  -1.48  -2.62  -2.36  -2.78  -1.49  \
0      -0.94  -1.03  -1.14  -2.50  -2.72  -1.48  -2.62  -2.36  -2.78  -1.49   
1      -0.94  -1.03  -1.14  -2.50  -2.72  -1.48  -2.62  -2.36  -2.78  -1.49   
2      -0.94  -1.03  -1.14  -2.50  -2.72  -1.48  -2.62  -2.36  -2.78  -1.49   
3      -0.94  -1.03  -1.14  -2.50  -2.72  -1.48  -2.62  -2.36  -2.78  -1.49   
4      -0.94  -1.03  -1.14  -2.50  -2.72  -1.48  -2.62  -2.36  -2.78  -1.49   
5      -0.94  -1.03  -1.14  -2.50  -2.72  -1.48  -2.62  -2.36  -2.78  -1.49   
6      -0.94  -1.03  -1.14  -2.50  -2.72  -1.48  -2.62  -2.36  -2.78  -1.49   
7      -0.94  -1.03  -1.14  -2.50  -2.72  -1.48  -2.62  -2.36  -2.78  -1.49   
8      -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
9      -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
10     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
11     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
12     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
13     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
14     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
15     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
16     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
17     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
18     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
19     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
20     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
21     -1.00  -1.11  -1.12  -2.47  -2.79  -1.48  -2.60  -2.33  -2.86  -1.57   
22     -1.07  -1.14  -1.19  -2.58  -3.02  -1.59  -3.06  -2.49  -3.01  -1.77   
23     -1.07  -1.14  -1.19  -2.58  -3.02  -1.59  -3.06  -2.49  -3.01  -1.77   
24     -1.07  -1.14  -1.19  -2.58  -3.02  -1.59  -3.06  -2.49  -3.01  -1.77   
25     -1.07  -1.14  -1.19  -2.58  -3.02  -1.59  -3.06  -2.49  -3.01  -1.77   
26     -1.07  -1.14  -1.19  -2.58  -3.02  -1.59  -3.06  -2.49  -3.01  -1.77   
27     -1.07  -1.14  -1.19  -2.58  -3.02  -1.59  -3.06  -2.49  -3.01  -1.77   
28     -1.07  -1.14  -1.19  -2.58  -3.02  -1.59  -3.06  -2.49  -3.01  -1.77   
29     -1.07  -1.14  -1.19  -2.58  -3.02  -1.59  -3.06  -2.49  -3.01  -1.77   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
39424  -0.62  -0.88  -0.74  -1.48  -1.47  -0.90  -2.30  -0.61  -1.70  -1.12   
39425  -0.62  -0.88  -0.74  -1.48  -1.47  -0.90  -2.30  -0.61  -1.70  -1.12   
39426  -0.62  -0.88  -0.74  -1.48  -1.47  -0.90  -2.30  -0.61  -1.70  -1.12   
39427  -0.64  -0.77  -0.86  -1.45  -1.43  -0.82  -2.43  -0.60  -1.85  -1.17   
39428  -0.64  -0.77  -0.86  -1.45  -1.43  -0.82  -2.43  -0.60  -1.85  -1.17   
39429  -0.64  -0.77  -0.86  -1.45  -1.43  -0.82  -2.43  -0.60  -1.85  -1.17   
39430  -0.64  -0.77  -0.86  -1.45  -1.43  -0.82  -2.43  -0.60  -1.85  -1.17   
39431  -0.64  -0.77  -0.86  -1.45  -1.43  -0.82  -2.43  -0.60  -1.85  -1.17   
39432  -0.64  -0.77  -0.86  -1.45  -1.43  -0.82  -2.43  -0.60  -1.85  -1.17   
39433  -0.64  -0.77  -0.86  -1.45  -1.43  -0.82  -2.43  -0.60  -1.85  -1.17   
39434  -0.65  -0.74  -0.90  -1.37  -1.54  -0.89  -2.64  -0.68  -1.88  -1.15   
39435  -0.65  -0.74  -0.90  -1.37  -1.54  -0.89  -2.64  -0.68  -1.88  -1.15   
39436  -0.65  -0.74  -0.90  -1.37  -1.54  -0.89  -2.64  -0.68  -1.88  -1.15   
39437  -0.65  -0.74  -0.90  -1.37  -1.54  -0.89  -2.64  -0.68  -1.88  -1.15   
39438  -0.65  -0.74  -0.90  -1.37  -1.54  -0.89  -2.64  -0.68  -1.88  -1.15   
39439  -0.65  -0.74  -0.90  -1.37  -1.54  -0.89  -2.64  -0.68  -1.88  -1.15   
39440  -0.65  -0.74  -0.90  -1.37  -1.54  -0.89  -2.64  -0.68  -1.88  -1.15   
39441  -0.65  -0.74  -0.90  -1.37  -1.54  -0.89  -2.64  -0.68  -1.88  -1.15   
39442  -0.65  -0.74  -0.90  -1.37  -1.54  -0.89  -2.64  -

In [7]:
indicatorEmotion

0.74519968  0.309802771  0.073476076  0.394173145  0.39579165  \
0        0.745200     0.309803     0.073476     0.394173    0.395792   
1        0.745200     0.309803     0.073476     0.394173    0.395792   
2        0.745200     0.309803     0.073476     0.394173    0.395792   
3        0.745200     0.309803     0.073476     0.394173    0.395792   
4        0.745200     0.309803     0.073476     0.394173    0.395792   
5        0.745200     0.309803     0.073476     0.394173    0.395792   
6        0.745200     0.309803     0.073476     0.394173    0.395792   
7        0.745200     0.309803     0.073476     0.394173    0.395792   
8        0.477053     0.349274     0.012148     0.333947    0.200081   
9        0.477053     0.349274     0.012148     0.333947    0.200081   
10       0.477053     0.349274     0.012148     0.333947    0.200081   
11       0.477053     0.349274     0.012148     0.333947    0.200081   
12       0.477053     0.349274     0.012148     0.333947    0.200081   
13       0.477053     0.349274     0.012148     0.333947    0.200081   
14       0.477053     0.349274     0.012148     0.333947    0.200081   
15       0.477053     0.349274     0.012148     0.333947    0.200081   
16       0.477053     0.349274     0.012148     0.333947    0.200081   
17       0.477053     0.349274     0.012148     0.333947    0.200081   
18       0.477053     0.349274     0.012148     0.333947    0.200081   
19       0.477053     0.349274     0.012148     0.333947    0.200081   
20       0.477053     0.349274     0.012148     0.333947    0.200081   
21       0.477053     0.349274     0.012148     0.333947    0.200081   
22       0.113787     0.031903    -0.025537     0.166151   -0.136116   
23       0.113787     0.031903    -0.025537     0.166151   -0.136116   
24       0.113787     0.031903    -0.025537     0.166151   -0.136116   
25       0.113787     0.031903    -0.025537     0.166151   -0.136116   
26       0.113787     0.031903    -0.025537     0.166151   -0.136116   
27       0.113787     0.031903    -0.025537     0.166151   -0.136116   
28       0.113787     0.031903    -0.025537     0.166151   -0.136116   
29       0.113787     0.031903    -0.025537     0.166151   -0.136116   
...           ...          ...          ...          ...         ...   
39424    2.696996     1.901449     1.693792     1.652370    0.523173   
39425    2.696996     1.901449     1.693792     1.652370    0.523173   
39426    2.696996     1.901449     1.693792     1.652370    0.523173   
39427    2.526427     1.681306     1.507362     1.446755    0.488399   
39428    2.526427     1.681306     1.507362     1.446755    0.488399   
39429    2.526427     1.681306     1.507362     1.446755    0.488399   
39430    2.526427     1.681306     1.507362     1.446755    0.488399   
39431    2.526427     1.681306     1.507362     1.446755    0.488399   
39432    2.526427     1.681306     1.507362     1.446755    0.488399   
39433    2.526427     1.681306     1.507362     1.446755    0.488399   
39434    2.512331     1.587743     1.483502     1.531661    0.483559   
39435    2.512331     1.587743     1.483502     1.531661    0.483559   
39436    2.512331     1.587743     1.483502     1.531661    0.483559   
39437    2.512331     1.587743     1.483502     1.531661    0.483559   
39438    2.512331     1.587743     1.483502     1.531661    0.483559   
39439    2.512331     1.587743     1.483502     1.531661    0.483559   
39440    2.512331     1.587743     1.483502     1.531661    0.483559   
39441    2.512331     1.587743     1.483502     1.531661    0.483559   
39442    2.512331     1.587743     1.483502     1.531661    0.483559   
39443    2.512331     1.587743     1.483502     1.531661    0.483559   
39444    2.545868     1.879423     1.683055     1.492661    0.470988   
39445    2.545868     1.879423     1.683055     1.492661    0.470988   
39446    2.545868     1.879423     1.683055     1.492661    0.470988   
39447    2.545868     1.879423     1.683055    

In [18]:
X = numpy.loadtxt("X.csv", delimiter=",")
Y = numpy.loadtxt("Y.csv", delimiter=",")
print(X)

[[-9.40000e-01 -1.03000e+00 -1.14000e+00 ...  1.06103e+03  6.60000e+01
   9.40000e-01]
 [-9.40000e-01 -1.03000e+00 -1.14000e+00 ...  1.06103e+03  6.60000e+01
   9.40000e-01]
 [-9.40000e-01 -1.03000e+00 -1.14000e+00 ...  1.06257e+03  6.60000e+01
   9.40000e-01]
 ...
 [-6.70000e-01 -8.60000e-01 -7.00000e-01 ...  1.76967e+03  6.40000e+01
   5.70000e-01]
 [-6.70000e-01 -8.60000e-01 -7.00000e-01 ...  1.76825e+03  6.40000e+01
   5.70000e-01]
 [-6.70000e-01 -8.60000e-01 -7.00000e-01 ...  1.76967e+03  6.40000e+01
   5.70000e-01]]


In [26]:
for cont in range(49):
    X[:,cont] = ((X[:,cont]-X[:,cont].min())/(X[:,cont].max()-X[:,cont].min()))
#               (x         -min(x))        /(max(x)         -min(x))
    
for cont in range(12):
#     Y[:,cont] = (Y[:,cont]/(Y[:,cont].max()))
    Y[:,cont] = ((Y[:,cont]-Y[:,cont].min())/(Y[:,cont].max()-Y[:,cont].min()))
    
    
print(X)


[[0.248      0.28965517 0.2027972  ... 0.07684807 0.35714286 0.86363636]
 [0.248      0.28965517 0.2027972  ... 0.07684807 0.35714286 0.86363636]
 [0.248      0.28965517 0.2027972  ... 0.0788502  0.35714286 0.86363636]
 ...
 [0.464      0.40689655 0.51048951 ... 0.99814088 0.30952381 0.02272727]
 [0.464      0.40689655 0.51048951 ... 0.99629476 0.30952381 0.02272727]
 [0.464      0.40689655 0.51048951 ... 0.99814088 0.30952381 0.02272727]]


In [48]:
# create model

model = Sequential()
model.add(Dense(49, input_dim=49, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(12, activation='sigmoid'))

In [49]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='ADAM',metrics=['accuracy'])

In [51]:
# Entrena al modelo
# Epochs = numero de veces que se entrena
model.fit(X,
          Y,
          epochs=500,
         shuffle=True)

Epoch 1/500
39455/39455 [==============================] - 2s 55us/step - loss: 0.5984 - acc: 0.0010
Epoch 2/500
39455/39455 [==============================] - 2s 55us/step - loss: 0.5984 - acc: 0.0010
Epoch 3/500
39455/39455 [==============================] - 2s 53us/step - loss: 0.5983 - acc: 0.0010
Epoch 4/500
39455/39455 [==============================] - 2s 62us/step - loss: 0.5983 - acc: 0.0010
Epoch 5/500
39455/39455 [==============================] - 2s 59us/step - loss: 0.5982 - acc: 0.0010
Epoch 6/500
39455/39455 [==============================] - 2s 60us/step - loss: 0.5981 - acc: 0.0010
Epoch 7/500
39455/39455 [==============================] - 2s 54us/step - loss: 0.5981 - acc: 0.0010
Epoch 8/500
39455/39455 [==============================] - 2s 59us/step - loss: 0.5981 - acc: 0.0010: 1s - loss
Epoch 9/500
39455/39455 [==============================] - 2s 53us/step - loss: 0.5980 - acc: 0.0010
Epoch 10/500
39455/39455 [==============================] - 2s 51us/step - loss:

39455/39455 [==============================] - 3s 66us/step - loss: 0.5975 - acc: 0.0010
Epoch 81/500
39455/39455 [==============================] - 3s 65us/step - loss: 0.5975 - acc: 0.0010
Epoch 82/500
39455/39455 [==============================] - 2s 57us/step - loss: 0.5975 - acc: 0.0010: 0s - loss: 0.5975 - acc: 0.001
Epoch 83/500
39455/39455 [==============================] - 2s 56us/step - loss: 0.5975 - acc: 0.0010
Epoch 84/500
39455/39455 [==============================] - 2s 53us/step - loss: 0.5974 - acc: 0.0010
Epoch 85/500
39455/39455 [==============================] - 2s 54us/step - loss: 0.5974 - acc: 0.0010
Epoch 86/500
39455/39455 [==============================] - 2s 56us/step - loss: 0.5975 - acc: 0.0010
Epoch 87/500
39455/39455 [==============================] - 3s 66us/step - loss: 0.5974 - acc: 0.0010
Epoch 88/500
39455/39455 [==============================] - 2s 61us/step - loss: 0.5974 - acc: 0.0010
Epoch 89/500
39455/39455 [==============================] - 2s 

39455/39455 [==============================] - 3s 67us/step - loss: 0.5974 - acc: 0.0010
Epoch 160/500
39455/39455 [==============================] - 3s 68us/step - loss: 0.5974 - acc: 0.0010
Epoch 161/500
39455/39455 [==============================] - 3s 66us/step - loss: 0.5974 - acc: 0.0010
Epoch 162/500
39455/39455 [==============================] - 3s 64us/step - loss: 0.5974 - acc: 0.0010
Epoch 163/500
39455/39455 [==============================] - 3s 65us/step - loss: 0.5974 - acc: 0.0010
Epoch 164/500
39455/39455 [==============================] - 2s 63us/step - loss: 0.5974 - acc: 0.0010
Epoch 165/500
39455/39455 [==============================] - 2s 50us/step - loss: 0.5974 - acc: 0.0010
Epoch 166/500
39455/39455 [==============================] - 2s 52us/step - loss: 0.5974 - acc: 0.0010
Epoch 167/500
39455/39455 [==============================] - 2s 50us/step - loss: 0.5974 - acc: 0.0010
Epoch 168/500
39455/39455 [==============================] - 2s 51us/step - loss: 0.597

39455/39455 [==============================] - 2s 61us/step - loss: 0.5973 - acc: 0.0010
Epoch 239/500
39455/39455 [==============================] - 3s 70us/step - loss: 0.5973 - acc: 0.0010
Epoch 240/500
39455/39455 [==============================] - 3s 64us/step - loss: 0.5973 - acc: 0.0010
Epoch 241/500
39455/39455 [==============================] - 3s 71us/step - loss: 0.5973 - acc: 0.0010
Epoch 242/500
39455/39455 [==============================] - 3s 67us/step - loss: 0.5973 - acc: 0.0010
Epoch 243/500
39455/39455 [==============================] - 3s 64us/step - loss: 0.5973 - acc: 0.0010
Epoch 244/500
39455/39455 [==============================] - 2s 63us/step - loss: 0.5973 - acc: 0.0010
Epoch 245/500
39455/39455 [==============================] - 3s 64us/step - loss: 0.5974 - acc: 0.0010
Epoch 246/500
39455/39455 [==============================] - 2s 63us/step - loss: 0.5973 - acc: 0.0010
Epoch 247/500
39455/39455 [==============================] - 3s 64us/step - loss: 0.597

39455/39455 [==============================] - 2s 63us/step - loss: 0.5973 - acc: 0.0010
Epoch 318/500
39455/39455 [==============================] - 3s 66us/step - loss: 0.5973 - acc: 0.0010
Epoch 319/500
39455/39455 [==============================] - 2s 51us/step - loss: 0.5973 - acc: 0.0010
Epoch 320/500
39455/39455 [==============================] - 2s 50us/step - loss: 0.5973 - acc: 0.0010
Epoch 321/500
39455/39455 [==============================] - 2s 54us/step - loss: 0.5973 - acc: 0.0010
Epoch 322/500
39455/39455 [==============================] - 2s 51us/step - loss: 0.5973 - acc: 0.0010
Epoch 323/500
39455/39455 [==============================] - 2s 57us/step - loss: 0.5973 - acc: 0.0010
Epoch 324/500
39455/39455 [==============================] - 2s 51us/step - loss: 0.5973 - acc: 0.0010
Epoch 325/500
39455/39455 [==============================] - 2s 58us/step - loss: 0.5973 - acc: 0.0010
Epoch 326/500
39455/39455 [==============================] - 2s 56us/step - loss: 0.597

39455/39455 [==============================] - 2s 50us/step - loss: 0.5973 - acc: 0.0010
Epoch 397/500
39455/39455 [==============================] - 2s 51us/step - loss: 0.5973 - acc: 0.0010
Epoch 398/500
39455/39455 [==============================] - 2s 52us/step - loss: 0.5974 - acc: 0.0010
Epoch 399/500
39455/39455 [==============================] - 2s 53us/step - loss: 0.5973 - acc: 0.0010
Epoch 400/500
39455/39455 [==============================] - 2s 52us/step - loss: 0.5973 - acc: 0.0010
Epoch 401/500
39455/39455 [==============================] - 2s 50us/step - loss: 0.5973 - acc: 0.0010
Epoch 402/500
39455/39455 [==============================] - 2s 52us/step - loss: 0.5974 - acc: 0.0010
Epoch 403/500
39455/39455 [==============================] - 2s 63us/step - loss: 0.5973 - acc: 0.0010
Epoch 404/500
39455/39455 [==============================] - 3s 65us/step - loss: 0.5973 - acc: 0.0010
Epoch 405/500
39455/39455 [==============================] - 3s 66us/step - loss: 0.597

39455/39455 [==============================] - 3s 65us/step - loss: 0.5973 - acc: 0.0010
Epoch 476/500
39455/39455 [==============================] - 3s 65us/step - loss: 0.5973 - acc: 0.0010
Epoch 477/500
39455/39455 [==============================] - 2s 63us/step - loss: 0.5973 - acc: 0.0010
Epoch 478/500
39455/39455 [==============================] - 3s 65us/step - loss: 0.5973 - acc: 0.0010
Epoch 479/500
39455/39455 [==============================] - 2s 63us/step - loss: 0.5973 - acc: 0.0010
Epoch 480/500
39455/39455 [==============================] - 3s 65us/step - loss: 0.5973 - acc: 0.0010
Epoch 481/500
39455/39455 [==============================] - 2s 58us/step - loss: 0.5973 - acc: 0.0010
Epoch 482/500
39455/39455 [==============================] - 2s 51us/step - loss: 0.5973 - acc: 0.0010
Epoch 483/500
39455/39455 [==============================] - 2s 53us/step - loss: 0.5973 - acc: 0.0010
Epoch 484/500
39455/39455 [==============================] - 2s 51us/step - loss: 0.597

In [47]:
predict = numpy.array(model.predict(X))
# Prediccion de la probabilidad de la emocion en base a los vectores
print(predict)

[[0.26157844 0.24882407 0.21235207 ... 0.9064122  0.26247764 0.08872195]
 [0.25882202 0.25744942 0.2148128  ... 0.90281254 0.2593365  0.09178315]
 [0.25894576 0.24463047 0.21606366 ... 0.9068945  0.26046517 0.08813933]
 ...
 [0.55176604 0.5679044  0.82143295 ... 0.40262797 0.5512143  0.5075857 ]
 [0.55220795 0.5662664  0.8217534  ... 0.40367517 0.55094093 0.5080075 ]
 [0.5513819  0.5668624  0.8225848  ... 0.40404066 0.55013525 0.5080323 ]]


In [45]:
# Valores reales de la prediccion
print(Y)

[[0.265234   0.22100066 0.21914537 ... 0.90047474 0.265234   0.10328152]
 [0.265234   0.22100066 0.21914537 ... 0.90047474 0.265234   0.10328152]
 [0.265234   0.22100066 0.21914537 ... 0.90047474 0.265234   0.10328152]
 ...
 [0.54457478 0.56813522 0.82301125 ... 0.41832588 0.54457478 0.50210618]
 [0.54457478 0.56813522 0.82301125 ... 0.41832588 0.54457478 0.50210618]
 [0.54457478 0.56813522 0.82301125 ... 0.41832588 0.54457478 0.50210618]]
