In [26]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Conv1D,Flatten

from keras.initializers import RandomNormal
import numpy


In [31]:
X = numpy.loadtxt("X.csv", delimiter=",")
Y = numpy.loadtxt("Y.csv", delimiter=",")
print(X)

[[-9.40000e-01 -1.03000e+00 -1.14000e+00 ...  1.06103e+03  6.60000e+01
   9.40000e-01]
 [-9.40000e-01 -1.03000e+00 -1.14000e+00 ...  1.06103e+03  6.60000e+01
   9.40000e-01]
 [-9.40000e-01 -1.03000e+00 -1.14000e+00 ...  1.06257e+03  6.60000e+01
   9.40000e-01]
 ...
 [-6.70000e-01 -8.60000e-01 -7.00000e-01 ...  1.76967e+03  6.40000e+01
   5.70000e-01]
 [-6.70000e-01 -8.60000e-01 -7.00000e-01 ...  1.76825e+03  6.40000e+01
   5.70000e-01]
 [-6.70000e-01 -8.60000e-01 -7.00000e-01 ...  1.76967e+03  6.40000e+01
   5.70000e-01]]


In [32]:
for cont in range(49):
    X[:,cont] = ((X[:,cont]-X[:,cont].min())/(X[:,cont].max()-X[:,cont].min()))
#               (x         -min(x))        /(max(x)         -min(x))
    
for cont in range(12):
    Y[:,cont] = (Y[:,cont]/(Y[:,cont].max()))
    
    
print(X)


[[0.248      0.28965517 0.2027972  ... 0.07684807 0.35714286 0.86363636]
 [0.248      0.28965517 0.2027972  ... 0.07684807 0.35714286 0.86363636]
 [0.248      0.28965517 0.2027972  ... 0.0788502  0.35714286 0.86363636]
 ...
 [0.464      0.40689655 0.51048951 ... 0.99814088 0.30952381 0.02272727]
 [0.464      0.40689655 0.51048951 ... 0.99629476 0.30952381 0.02272727]
 [0.464      0.40689655 0.51048951 ... 0.99814088 0.30952381 0.02272727]]


In [48]:
# create model

model = Sequential()
model.add(Dense(49, input_dim=49, activation='relu'))
model.add(Dense(100, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

In [61]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='ADAM')

In [60]:
# Fit the model
model.fit(X,
          Y[:,1],
          epochs=10,
         shuffle=True)

Epoch 1/1
39455/39455 [==============================] - 2s 47us/step - loss: 0.3802


In [59]:
model.predict(X)

array([[0.09222101],
       [0.09028205],
       [0.08885828],
       ...,
       [0.48770902],
       [0.48817626],
       [0.4882905 ]], dtype=float32)

In [38]:
print(Y[:,1])

[0.08084279 0.08084279 0.08084279 ... 0.49043394 0.49043394 0.49043394]
