# Competencia en Kaggle: Titanic: Machine Learning from Disaster

# 1. Crea una cuenta en Kaggle https://www.kaggle.com/

# 2. Ejecuta las celdas 

In [125]:
import pandas as pd

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
validate = pd.read_csv('gender_submission.csv')

# Drop features-... is this good?

In [126]:
train = train.drop(['Name', 'Ticket', 'Cabin', 'Embarked'],axis=1)
test = test.drop(['Name', 'Ticket', 'Cabin', 'Embarked'],axis=1)

train.head(10)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0            1         0       3    male  22.0      1      0   7.2500
1            2         1       1  female  38.0      1      0  71.2833
2            3         1       3  female  26.0      0      0   7.9250
3            4         1       1  female  35.0      1      0  53.1000
4            5         0       3    male  35.0      0      0   8.0500
5            6         0       3    male   NaN      0      0   8.4583
6            7         0       1    male  54.0      0      0  51.8625
7            8         0       3    male   2.0      3      1  21.0750
8            9         1       3  female  27.0      0      2  11.1333
9           10         1       2  female  14.0      1      0  30.0708

# Sex mapping 1 - male, 0 - female

In [127]:
train['Sex_binary']=train['Sex'].map({'male':1,'female':0})
test['Sex_binary']=test['Sex'].map({'male':1,'female':0})


# Age cleaning

In [128]:
train['Age'] = train['Age'].fillna(train['Age'].mean())
test['Age'] = test['Age'].fillna(train['Age'].mean())

In [129]:
features = ['Pclass','Age','Sex_binary','SibSp','Parch','Fare']
target = 'Survived'

In [130]:
train[features].head(3)

Pclass   Age  Sex_binary  SibSp  Parch     Fare
0       3  22.0           1      1      0   7.2500
1       1  38.0           0      1      0  71.2833
2       3  26.0           0      0      0   7.9250

In [131]:
import numpy as np

In [132]:
X_train = np.array(train[features])
X_train

array([[ 3.        , 22.        ,  1.        ,  1.        ,  0.        ,
         7.25      ],
       [ 1.        , 38.        ,  0.        ,  1.        ,  0.        ,
        71.2833    ],
       [ 3.        , 26.        ,  0.        ,  0.        ,  0.        ,
         7.925     ],
       ...,
       [ 3.        , 29.69911765,  0.        ,  1.        ,  2.        ,
        23.45      ],
       [ 1.        , 26.        ,  1.        ,  0.        ,  0.        ,
        30.        ],
       [ 3.        , 32.        ,  1.        ,  0.        ,  0.        ,
         7.75      ]])

In [133]:
y_train = np.array(train[target])
y_train = y_train.reshape(-1,1)
y_train

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [134]:
# Import keras modules
from keras.models import Sequential
from keras.layers import Dense
from keras.initializers import glorot_normal

In [214]:
model = Sequential()
model.add(Dense(6, input_dim=6, activation='relu', kernel_initializer="uniform"))
model.add(Dense(40, activation='sigmoid', kernel_initializer="uniform"))
model.add(Dense(20, activation='sigmoid', kernel_initializer="uniform"))
model.add(Dense(1, activation='sigmoid', kernel_initializer="uniform"))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [215]:
model.fit(X_train, y_train, epochs=200)

Epoch 1/200
891/891 [==============================] - 3s 4ms/step - loss: 0.6773 - acc: 0.6162
Epoch 2/200
891/891 [==============================] - 0s 175us/step - loss: 0.6669 - acc: 0.6162
Epoch 3/200
891/891 [==============================] - 0s 158us/step - loss: 0.6629 - acc: 0.6162
Epoch 4/200
891/891 [==============================] - 0s 210us/step - loss: 0.6598 - acc: 0.6162
Epoch 5/200
891/891 [==============================] - ETA: 0s - loss: 0.6618 - acc: 0.605 - 0s 175us/step - loss: 0.6566 - acc: 0.6162
Epoch 6/200
891/891 [==============================] - 0s 158us/step - loss: 0.6530 - acc: 0.6162
Epoch 7/200
891/891 [==============================] - 0s 158us/step - loss: 0.6497 - acc: 0.6162
Epoch 8/200
891/891 [==============================] - 0s 158us/step - loss: 0.6450 - acc: 0.6162
Epoch 9/200
891/891 [==============================] - 0s 158us/step - loss: 0.6404 - acc: 0.6162
Epoch 10/200
891/891 [==============================] - 0s 175us/step - loss: 0.63

891/891 [==============================] - 0s 175us/step - loss: 0.4987 - acc: 0.7890
Epoch 84/200
891/891 [==============================] - 0s 210us/step - loss: 0.4976 - acc: 0.7868
Epoch 85/200
891/891 [==============================] - 0s 193us/step - loss: 0.4989 - acc: 0.7879
Epoch 86/200
891/891 [==============================] - 0s 210us/step - loss: 0.4980 - acc: 0.7901
Epoch 87/200
891/891 [==============================] - 0s 193us/step - loss: 0.4989 - acc: 0.7901
Epoch 88/200
891/891 [==============================] - 0s 175us/step - loss: 0.4969 - acc: 0.7890
Epoch 89/200
891/891 [==============================] - 0s 175us/step - loss: 0.4994 - acc: 0.7879
Epoch 90/200
891/891 [==============================] - 0s 210us/step - loss: 0.4981 - acc: 0.7901
Epoch 91/200
891/891 [==============================] - 0s 193us/step - loss: 0.4975 - acc: 0.7924
Epoch 92/200
891/891 [==============================] - 0s 190us/step - loss: 0.4999 - acc: 0.7868
Epoch 93/200
891/891 [=

891/891 [==============================] - 0s 210us/step - loss: 0.4907 - acc: 0.7789
Epoch 165/200
891/891 [==============================] - 0s 193us/step - loss: 0.4881 - acc: 0.7890
Epoch 166/200
891/891 [==============================] - 0s 175us/step - loss: 0.4911 - acc: 0.7868
Epoch 167/200
891/891 [==============================] - 0s 175us/step - loss: 0.4888 - acc: 0.7868
Epoch 168/200
891/891 [==============================] - 0s 193us/step - loss: 0.4880 - acc: 0.7868
Epoch 169/200
891/891 [==============================] - 0s 175us/step - loss: 0.4876 - acc: 0.7901
Epoch 170/200
891/891 [==============================] - 0s 158us/step - loss: 0.4882 - acc: 0.7879
Epoch 171/200
891/891 [==============================] - 0s 175us/step - loss: 0.4868 - acc: 0.7868
Epoch 172/200
891/891 [==============================] - 0s 193us/step - loss: 0.4868 - acc: 0.7901
Epoch 173/200
891/891 [==============================] - 0s 175us/step - loss: 0.4863 - acc: 0.7890
Epoch 174/200


In [220]:
X_test = np.array(test[features])
X_test

array([[ 3.        , 34.5       ,  1.        ,  0.        ,  0.        ,
         7.8292    ],
       [ 3.        , 47.        ,  0.        ,  1.        ,  0.        ,
         7.        ],
       [ 2.        , 62.        ,  1.        ,  0.        ,  0.        ,
         9.6875    ],
       ...,
       [ 3.        , 38.5       ,  1.        ,  0.        ,  0.        ,
         7.25      ],
       [ 3.        , 29.69911765,  1.        ,  0.        ,  0.        ,
         8.05      ],
       [ 3.        , 29.69911765,  1.        ,  1.        ,  1.        ,
        22.3583    ]])

In [221]:
predicciones = model.predict(X_test)
print(predicciones)


[[0.13648072]
 [0.30357546]
 [0.13648072]
 [0.13648072]
 [0.4839842 ]
 [0.1695304 ]
 [0.69808555]
 [0.18107265]
 [0.7394202 ]
 [0.13648072]
 [0.13648072]
 [0.15071245]
 [0.8804762 ]
 [0.13648072]
 [0.8592766 ]
 [0.7622017 ]
 [0.13648072]
 [0.14055313]
 [0.47087997]
 [0.6137224 ]
 [0.27204165]
 [0.15687397]
 [0.8398698 ]
 [0.588166  ]
 [0.8787709 ]
 [0.13648072]
 [0.8742017 ]
 [0.13704543]
 [0.19140954]
 [0.13648072]
 [0.13648072]
 [0.14035822]
 [0.45902848]
 [0.5407374 ]
 [0.3941871 ]
 [0.14673392]
 [0.70447713]
 [0.7431107 ]
 [0.1407353 ]
 [0.51775986]
 [0.13648072]
 [0.20733643]
 [0.13648072]
 [0.7435462 ]
 [0.8422675 ]
 [0.13648072]
 [0.17295118]
 [0.13648072]
 [0.8839147 ]
 [0.623331  ]
 [0.45258462]
 [0.15517546]
 [0.3967623 ]
 [0.87654114]
 [0.1505262 ]
 [0.13648072]
 [0.13648072]
 [0.13648072]
 [0.13648072]
 [0.88718176]
 [0.15383561]
 [0.13648072]
 [0.15045062]
 [0.7306003 ]
 [0.85716283]
 [0.80191237]
 [0.74548465]
 [0.25578234]
 [0.21643454]
 [0.8769799 ]
 [0.7236042 ]
 [0.14

In [222]:
predicciones = predicciones.tolist()

In [223]:
pre = pd.Series(predicciones)
validate['prediccion'] = pre
validate['prediccion'] = validate['prediccion'].str.get(0)
validate

PassengerId  Survived  prediccion  final
0            892         0    0.136481      0
1            893         1    0.303575      1
2            894         0    0.136481      0
3            895         0    0.136481      0
4            896         1    0.483984      1
5            897         0    0.169530      0
6            898         1    0.698086      1
7            899         0    0.181073      0
8            900         1    0.739420      1
9            901         0    0.136481      0
10           902         0    0.136481      0
11           903         0    0.150712      0
12           904         1    0.880476      1
13           905         0    0.136481      0
14           906         1    0.859277      1
15           907         1    0.762202      1
16           908         0    0.136481      0
17           909         0    0.140553      0
18           910         1    0.470880      1
19           911         1    0.613722      1
20           912         0    0.272042      0
21           913         0    0.156874      1
22           914         1    0.839870      1
23           915         0    0.588166      1
24           916         1    0.878771      1
25           917         0    0.136481      0
26           918         1    0.874202      1
27           919         0    0.137045      0
28           920         0    0.191410      0
29           921         0    0.136481      0
..           ...       ...         ...    ...
388         1280         0    0.142825      0
389         1281         0    0.136481      0
390         1282         0    0.804829      1
391         1283         1    0.819931      1
392         1284         0    0.265694      1
393         1285         0    0.136481      0
394         1286         0    0.136481      0
395         1287         1    0.868012      1
396         1288         0    0.136481      0
397         1289         1    0.870434      1
398         1290         0    0.140519      0
399         1291         0    0.136481      0
400         1292         1    0.887825      1
401         1293         0    0.136481      0
402         1294         1    0.872585      1
403         1295         0    0.469832      1
404         1296         0    0.136481      0
405         1297         0    0.169558      0
406         1298         0    0.136481      0
407         1299         0    0.864563      1
408         1300         1    0.700506      1
409         1301         1    0.634506      1
410         1302         1    0.700862      1
411         1303         1    0.882606      1
412         1304         1    0.708269      1
413         1305         0    0.136481      0
414         1306         1    0.888434      1
415         1307         0    0.136481      0
416         1308         0    0.136481      0
417         1309         0    0.142586      0

[418 rows x 4 columns]

In [224]:
coincidencias = []
for dato in validate.prediccion:
    if dato >= 0.5:
        coincidencias.append(1)
    else:
        coincidencias.append(0)
validate['final'] = coincidencias
validate

PassengerId  Survived  prediccion  final
0            892         0    0.136481      0
1            893         1    0.303575      0
2            894         0    0.136481      0
3            895         0    0.136481      0
4            896         1    0.483984      0
5            897         0    0.169530      0
6            898         1    0.698086      1
7            899         0    0.181073      0
8            900         1    0.739420      1
9            901         0    0.136481      0
10           902         0    0.136481      0
11           903         0    0.150712      0
12           904         1    0.880476      1
13           905         0    0.136481      0
14           906         1    0.859277      1
15           907         1    0.762202      1
16           908         0    0.136481      0
17           909         0    0.140553      0
18           910         1    0.470880      0
19           911         1    0.613722      1
20           912         0    0.272042      0
21           913         0    0.156874      0
22           914         1    0.839870      1
23           915         0    0.588166      1
24           916         1    0.878771      1
25           917         0    0.136481      0
26           918         1    0.874202      1
27           919         0    0.137045      0
28           920         0    0.191410      0
29           921         0    0.136481      0
..           ...       ...         ...    ...
388         1280         0    0.142825      0
389         1281         0    0.136481      0
390         1282         0    0.804829      1
391         1283         1    0.819931      1
392         1284         0    0.265694      0
393         1285         0    0.136481      0
394         1286         0    0.136481      0
395         1287         1    0.868012      1
396         1288         0    0.136481      0
397         1289         1    0.870434      1
398         1290         0    0.140519      0
399         1291         0    0.136481      0
400         1292         1    0.887825      1
401         1293         0    0.136481      0
402         1294         1    0.872585      1
403         1295         0    0.469832      0
404         1296         0    0.136481      0
405         1297         0    0.169558      0
406         1298         0    0.136481      0
407         1299         0    0.864563      1
408         1300         1    0.700506      1
409         1301         1    0.634506      1
410         1302         1    0.700862      1
411         1303         1    0.882606      1
412         1304         1    0.708269      1
413         1305         0    0.136481      0
414         1306         1    0.888434      1
415         1307         0    0.136481      0
416         1308         0    0.136481      0
417         1309         0    0.142586      0

[418 rows x 4 columns]

In [225]:
coincide = 0
coincide = sum(validate['Survived'] == validate['final'])
print(coincide/ len(validate))


match = 0
nomatch = 0
for val in validate.values:
    if val[1] == val[3]:
        match = match +1
    else:
        nomatch = nomatch +1
print(match/len(validate))

0.9043062200956937
0.9043062200956937


In [226]:
toKaggle = pd.DataFrame({'PassengerId':validate['PassengerId'],
                         'Survived':validate['final']})

toKaggle.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

# output file with your prediction

In [227]:
from datetime import datetime

archivo = 'Titanic01'+'.csv'

toKaggle.to_csv(archivo,index=False)

print('Creado: ' + archivo)

Creado: Titanic01.csv
